### PR TITLE
Make explicit support for Python 2 and 3

### PR DESCRIPTION
**Pull request by cclauss**
Arvados-DCO-1.1-Signed-off-by: Chris Clauss <cclauss@bluewin.ch>

### CODE REVIEW

**Comment by tfmorris** [comment]
LGTM. Sorry for the delay in reviewing.

@tomclegg WDYT?

**Comment by tomclegg** [comment]
LGTM.

Sorry this is red tape, but we now require a DCO sign-off line in each commit message. @cclauss, if you reword your commit to include this, I can merge. See https://dev.arvados.org/projects/arvados/wiki/Developer_Certificate_Of_Origin

Thanks!

**Comment by cclauss** [comment]
@tomclegg Thoughts?

**Comment by tfmorris** [comment]
@cclauss I just noticed that you added your DCO sign-off line to the Github comment which is probably why @tomclegg didn't notice it.

If you do a git commit --amend and add it to the end of commit message itself, we should be all set.

Sorry for all the hoops!

**Pull request closed without merging**
