### PR TITLE
14075 fix slow queries in python commands sdk `uploadfiles`

### PR DESCRIPTION
**Pull request by jrandall**
change `uploadfiles` to include pdh in name of collection rather then using `ensure_unique_names=True`
also don't bother attempting to list existing empty collections as this always exists

Arvados-DCO-1.1-Signed-off-by: Joshua C. Randall <jcrandall@alum.mit.edu>

### CODE REVIEW

**Comment by jrandall** [comment]
This is built against 1.1.4.20180607205857 as that is what we are running for our arvados-jobs containers currently and we don't want to make too many changes in the middle of an analysis workflow. I'll work on rebasing it to the current master once we are back up and running.

**Comment by tetron** [comment]
I'm working on fixing this up and will merge it.

**Comment by tfmorris** [comment]
Thanks @tetron -- and thanks @jrandall for the fix! 

To make it easier to find the original issue (because we don't use the Github issue tracker) here's a direct link https://dev.arvados.org/issues/14075

**Comment by tetron** [comment]
This was merged in 5b8dfb5d5f4b34fa730e69c45c517f0cfb3fdc9f (github isn't picking it up because it was also rebased)

**Pull request closed without merging**
